-- Seed file for Supabase PostgreSQL Database (Numeric IDs)

-- 1. CREATE TABLES
CREATE TABLE IF NOT EXISTS categories (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    description TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS locations (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    taluk VARCHAR(100) NOT NULL,
    UNIQUE (name, taluk)
);

CREATE TABLE IF NOT EXISTS inquiries (
    id BIGSERIAL PRIMARY KEY,
    category_id INTEGER NOT NULL REFERENCES categories(id),
    location_id INTEGER NOT NULL REFERENCES locations(id),
    description TEXT NOT NULL,
    rating INTEGER NOT NULL CHECK (rating >= 1 AND rating <= 5),
    complainant_name VARCHAR(255),
    complainant_phone VARCHAR(20),
    feedback TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 2. SEED CATEGORIES
INSERT INTO categories (name, description) VALUES ('DATA & IDENTITY THEFT', 'Stealing information or impersonating credentials') ON CONFLICT (name) DO UPDATE SET description = EXCLUDED.description;
INSERT INTO categories (name, description) VALUES ('FINANCIAL EXTORTION', 'Holding systems or information hostage for ransom') ON CONFLICT (name) DO UPDATE SET description = EXCLUDED.description;
INSERT INTO categories (name, description) VALUES ('SYSTEM DISRUPTION', 'Breaking digital architecture or compromising service availability') ON CONFLICT (name) DO UPDATE SET description = EXCLUDED.description;
INSERT INTO categories (name, description) VALUES ('PERSONAL HARASSMENT', 'Directly targeting, intimidating, or exposing individual targets') ON CONFLICT (name) DO UPDATE SET description = EXCLUDED.description;
INSERT INTO categories (name, description) VALUES ('Other', 'Select this category if your inquiry does not match standard options.') ON CONFLICT (name) DO UPDATE SET description = EXCLUDED.description;

-- 3. SEED LOCATIONS
INSERT INTO locations (name, taluk) VALUES ('Agali', 'Chittur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Agali Town', 'Mannarkkad') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Akathethara', 'Palakkad') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Alanallur', 'Chittur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Alanallur-I', 'Chittur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Alanallur-II', 'Chittur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Alanallur-III', 'Chittur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Alathur', 'Alathur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Alathur Town', 'Alathur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Ambalapara', 'Ottapalam') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Ambalapara-I', 'Ottapalam') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Ambalapara-II', 'Ottapalam') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Anakkara', 'Ottapalam') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Anakkara', 'Pattambi') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Ananganadi', 'Ottapalam') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Anginda Peak', 'Mannarkkad') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Attappadi', 'Chittur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Ayilur', 'Chittur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Bhavani River', 'Mannarkkad') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Calicut Bypass', 'Palakkad') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Chalavara', 'Ottapalam') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Chalissery', 'Ottapalam') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Chalissery', 'Pattambi') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Cherpulassery', 'Ottapalam') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Cherpulassery Town', 'Ottapalam') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Chittur', 'Chittur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Chittur Town', 'Chittur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Chittur-Thathamangalam', 'Chittur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Civil Station', 'Palakkad') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Coyalmannam', 'Alathur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Coyalmannam', 'Palakkad') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Coyalmannam-I', 'Alathur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Coyalmannam-II', 'Alathur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Dhoni', 'Chittur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Dhoni Waterfalls', 'Chittur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('East Yakkara', 'Palakkad') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Elappully', 'Palakkad') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Elappully-I', 'Palakkad') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Elappully-II', 'Palakkad') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Elavanchery', 'Chittur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Elivai Mala', 'Chittur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Erimayur', 'Alathur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Erimayur', 'Palakkad') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Erimayur-I', 'Alathur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Erimayur-II', 'Alathur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Eruthiyampathy', 'Chittur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Fantasy Park', 'Chittur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Fort Maidan', 'Palakkad') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Hemambikanagar', 'Palakkad') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Jainimedu', 'Palakkad') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Kadalundi River', 'Mannarkkad') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Kadampazhipuram', 'Ottapalam') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Kadampazhipuram-I', 'Ottapalam') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Kadampazhipuram-II', 'Ottapalam') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Kallamala', 'Chittur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Kalpathy', 'Palakkad') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Kalpathy River', 'Palakkad') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Kanjikode', 'Palakkad') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Kanjirapuzha', 'Chittur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Kanjirapuzha Dam', 'Chittur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Kannadi', 'Palakkad') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Kannambra', 'Alathur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Kannambra', 'Palakkad') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Kannambra-I', 'Alathur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Kannambra-I', 'Palakkad') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Kannambra-II', 'Alathur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Kannambra-II', 'Palakkad') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Kannimara Teak', 'Chittur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Kappur', 'Ottapalam') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Kappur', 'Pattambi') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Karakurussi', 'Chittur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Karimba', 'Chittur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Karimba-I', 'Chittur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Karimba-II', 'Chittur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Karimpuzha', 'Ottapalam') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Karimpuzha Kovilakam', 'Chittur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Karimpuzha-I', 'Ottapalam') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Karimpuzha-II', 'Ottapalam') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Kavassery', 'Alathur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Kavassery', 'Palakkad') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Kavassery-I', 'Alathur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Kavassery-I', 'Palakkad') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Kavassery-II', 'Alathur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Kavassery-II', 'Palakkad') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Kayaradi', 'Chittur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Keralassery', 'Palakkad') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Kizhakkencheri', 'Alathur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Kizhakkencheri', 'Palakkad') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Kizhakkencheri-I', 'Alathur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Kizhakkencheri-I', 'Palakkad') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Kizhakkencheri-II', 'Alathur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Kizhakkencheri-II', 'Palakkad') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Kodumba', 'Palakkad') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Kodumbu', 'Palakkad') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Koduvayoor', 'Chittur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Koduvayur', 'Chittur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Koduvayur-I', 'Chittur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Koduvayur-II', 'Chittur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Kollengode', 'Chittur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Kollengode Town', 'Chittur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Kongad', 'Palakkad') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Kongad-I', 'Palakkad') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Kongad-II', 'Palakkad') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Koppam', 'Ottapalam') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Koppam', 'Pattambi') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Koppam Town', 'Ottapalam') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Koppam Town', 'Pattambi') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Kottappadam', 'Palakkad') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Kottappuram', 'Alathur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Kottappuram', 'Palakkad') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Kottappuram-I', 'Alathur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Kottappuram-II', 'Alathur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Kottathara', 'Chittur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Kottayi', 'Alathur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Kottayi', 'Palakkad') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Kottayi-I', 'Alathur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Kottayi-I', 'Palakkad') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Kottayi-II', 'Alathur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Kottayi-II', 'Palakkad') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Kottopadam', 'Chittur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Kottopadam-I', 'Chittur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Kottopadam-II', 'Chittur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Kottopadam-III', 'Chittur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Kozhinjampara', 'Chittur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Kozhinjampara Town', 'Chittur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Kozhipathy', 'Chittur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('KSRTC Bus Stand', 'Palakkad') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Kulukkallur', 'Ottapalam') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Kulukkallur', 'Pattambi') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Kulukkallur Town', 'Ottapalam') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Kulukkallur Town', 'Pattambi') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Kumaramputhur', 'Chittur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Kumaramputhur-I', 'Chittur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Kumaramputhur-II', 'Chittur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Kunthipuzha', 'Mannarkkad') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Kuthanur', 'Alathur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Kuthanur', 'Palakkad') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Kuthanur-I', 'Alathur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Kuthanur-I', 'Palakkad') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Kuthanur-II', 'Alathur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Kuthanur-II', 'Palakkad') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Kuzhalmannam', 'Alathur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Kuzhalmannam', 'Palakkad') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Kuzhalmannam-I', 'Alathur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Kuzhalmannam-I', 'Palakkad') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Kuzhalmannam-II', 'Alathur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Kuzhalmannam-II', 'Palakkad') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Lakkidi', 'Ottapalam') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Lakkidi-Perur', 'Ottapalam') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Lakkidi-Perur-I', 'Ottapalam') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Lakkidi-Perur-II', 'Ottapalam') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Malampuzha', 'Palakkad') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Malampuzha Dam', 'Palakkad') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Mampara Peak', 'Chittur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Mangalam Dam', 'Alathur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Mangalam Dam', 'Palakkad') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Mankara', 'Palakkad') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Mannarkkad', 'Chittur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Mannarkkad Town', 'Mannarkkad') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Mannarkkad-I', 'Mannarkkad') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Mannarkkad-II', 'Mannarkkad') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Mannur', 'Palakkad') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Marutharoad', 'Palakkad') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Marutharode', 'Palakkad') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Mathur', 'Alathur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Mathur', 'Palakkad') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Mathur-I', 'Alathur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Mathur-I', 'Palakkad') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Mathur-II', 'Alathur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Mathur-II', 'Palakkad') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Meenkara', 'Chittur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Meenkara Dam', 'Chittur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Meenvallam', 'Chittur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Meenvallam Waterfalls', 'Chittur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Melarkode', 'Alathur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Melarkode', 'Palakkad') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Moolathara', 'Chittur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Mukurthi', 'Mannarkkad') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Mukurthi Peak', 'Mannarkkad') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Mundur', 'Palakkad') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Mundur-I', 'Palakkad') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Mundur-II', 'Palakkad') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Municipal Bus Stand', 'Palakkad') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Muthalamada', 'Chittur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Muthalamada-I', 'Chittur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Muthalamada-II', 'Chittur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Muthuthala', 'Pattambi') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Muthuthala Town', 'Pattambi') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Nagalassery', 'Ottapalam') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Nagalassery', 'Pattambi') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Nalleppilly', 'Chittur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Nellaya', 'Ottapalam') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Nellaya Town', 'Ottapalam') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Nelliyampathy', 'Chittur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Nelliyampathy Hills', 'Chittur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Nemmara', 'Chittur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Nemmara Town', 'Chittur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('New Amarambalam', 'Chittur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('New Kalpathy', 'Palakkad') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Olavakkode', 'Palakkad') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Old Kalpathy', 'Palakkad') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Ongallur', 'Ottapalam') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Ongallur', 'Pattambi') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Ongallur-I', 'Ottapalam') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Ongallur-I', 'Pattambi') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Ongallur-II', 'Ottapalam') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Ongallur-II', 'Pattambi') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Ottapalam', 'Ottapalam') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Ottapalam Railway Station', 'Ottapalam') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Ottapalam Town', 'Ottapalam') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Ozhalapathy', 'Chittur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Padavayal', 'Chittur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Palakayam', 'Chittur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Palakkad', 'Palakkad') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Palakkad Fort', 'Palakkad') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Palakkad Junction', 'Ottapalam') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Palakkad Town', 'Palakkad') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Palakkad Town Railway Station', 'Ottapalam') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Pallassana', 'Chittur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Parambikulam', 'Chittur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Parambikulam Dam', 'Chittur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Parambikulam Tiger Reserve', 'Chittur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Parli', 'Palakkad') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Parli-I', 'Palakkad') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Parli-II', 'Palakkad') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Paruthur', 'Ottapalam') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Paruthur', 'Pattambi') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Paruthur Town', 'Ottapalam') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Paruthur Town', 'Pattambi') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Pattambi', 'Ottapalam') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Pattambi', 'Pattambi') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Pattambi Town', 'Ottapalam') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Pattambi Town', 'Pattambi') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Pattithara', 'Ottapalam') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Pattithara', 'Pattambi') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Payyanadam', 'Chittur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Perukotukurussi', 'Alathur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Perukotukurussi', 'Palakkad') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Perukotukurussi-I', 'Alathur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Perukotukurussi-I', 'Palakkad') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Perukotukurussi-II', 'Alathur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Perukotukurussi-II', 'Palakkad') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Perumatty', 'Chittur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Peruvemba', 'Palakkad') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Pirayiri', 'Palakkad') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Polpully', 'Palakkad') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Pookkottukavu', 'Ottapalam') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Pookottukavu', 'Ottapalam') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Pothundi', 'Chittur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Pothundi Dam', 'Chittur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Pottassery', 'Chittur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Pottassery-I', 'Chittur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Pottassery-II', 'Chittur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Pudunagaram', 'Chittur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Puduppariyaram', 'Palakkad') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Pudussery', 'Palakkad') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Pudussery Central', 'Palakkad') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Pudussery East', 'Palakkad') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Pudussery West', 'Palakkad') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Puthukode', 'Alathur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Puthukode', 'Palakkad') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Puthur', 'Chittur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Sekharipuram', 'Chittur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Sholayur', 'Chittur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Shoranur', 'Ottapalam') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Shoranur Junction', 'Ottapalam') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Shoranur Junction Railway Station', 'Ottapalam') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Shoranur Town', 'Ottapalam') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Shornur', 'Ottapalam') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Silent Valley', 'Chittur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Silent Valley National Park', 'Chittur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Siruvani', 'Chittur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Siruvani Dam', 'Chittur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Siruvani Waterfalls', 'Chittur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Sreekrishnapuram', 'Ottapalam') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Sreekrishnapuram-I', 'Ottapalam') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Sreekrishnapuram-II', 'Ottapalam') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Stadium Bypass', 'Palakkad') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Stadium Stand', 'Palakkad') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Sultanpet', 'Palakkad') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Tarur', 'Alathur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Tarur', 'Palakkad') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Tarur-I', 'Alathur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Tarur-I', 'Palakkad') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Tarur-II', 'Alathur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Tarur-II', 'Palakkad') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Thachampara', 'Chittur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Thachanattukara', 'Chittur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Thachanattukara-I', 'Chittur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Thachanattukara-II', 'Chittur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Thattamangalam', 'Chittur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Thekkedesam', 'Chittur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Thenkurussi', 'Alathur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Thenkurussi', 'Palakkad') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Thenkurussi-I', 'Alathur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Thenkurussi-I', 'Palakkad') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Thenkurussi-II', 'Alathur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Thenkurussi-II', 'Palakkad') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Thiriuvegapura', 'Ottapalam') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Thirumittakode', 'Ottapalam') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Thirumittakode', 'Pattambi') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Thirumittakode-I', 'Ottapalam') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Thirumittakode-I', 'Pattambi') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Thirumittakode-II', 'Ottapalam') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Thirumittakode-II', 'Pattambi') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Thiruvazhiyode', 'Chittur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Thiruvegapura', 'Pattambi') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Thrikkadeeri', 'Ottapalam') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Thrikkadeeri-I', 'Ottapalam') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Thrikkadeeri-II', 'Ottapalam') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Thrithala', 'Ottapalam') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Thrithala', 'Pattambi') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Thrithala Town', 'Ottapalam') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Thrithala Town', 'Pattambi') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Town Bus Stand', 'Palakkad') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Vadakarapathy', 'Chittur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Vadakkencheri', 'Alathur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Vadakkencheri', 'Palakkad') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Vadakkencheri-I', 'Alathur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Vadakkencheri-I', 'Palakkad') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Vadakkencheri-II', 'Alathur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Vadakkencheri-II', 'Palakkad') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Vadavannur', 'Chittur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Vallangi', 'Chittur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Vallapuzha', 'Ottapalam') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Vallapuzha', 'Pattambi') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Vallapuzha Town', 'Ottapalam') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Vallapuzha Town', 'Pattambi') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Valliyavallampathy', 'Chittur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Vandazhi', 'Alathur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Vandazhi', 'Palakkad') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Vandazhi-I', 'Alathur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Vandazhi-I', 'Palakkad') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Vandazhi-II', 'Alathur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Vandazhi-II', 'Palakkad') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Vandithavalam', 'Chittur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Vaniyamkulam', 'Ottapalam') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Vaniyamkulam-I', 'Ottapalam') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Vaniyamkulam-II', 'Ottapalam') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Varikkasseri Mana', 'Chittur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Vellinezhi', 'Ottapalam') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Vellinezhi Town', 'Ottapalam') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Vilayur', 'Ottapalam') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Vilayur', 'Pattambi') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Vilayur Town', 'Ottapalam') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Vilayur Town', 'Pattambi') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Walayar', 'Chittur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Walayar Dam', 'Chittur') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('West Yakkara', 'Palakkad') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Yakkara', 'Palakkad') ON CONFLICT (name, taluk) DO NOTHING;
INSERT INTO locations (name, taluk) VALUES ('Other', 'Other') ON CONFLICT (name, taluk) DO NOTHING;
